### ISSUE TITLE
By bigger window, line in middle of the edditing section

### ISSUE THREAD

**Issue by Clon1998** [nevadascout/Dash#66]
![sadasd23423nannt](https://cloud.githubusercontent.com/assets/10357775/6824140/8598af70-d2ef-11e4-8b47-02ebcff0f33b.PNG)
Having a line in the middle of the edit section when i make the window bigger

**Comment by nevadascout** [comment]
This is the ruler that marks the 80 character width from the left margin.

You can disable it in Edit -> Settings by unticking the "show ruler" option, then restarting Dash.

**Comment by Clon1998** [comment]
Ty
